FROM golang

ENV GOPATH /go

WORKDIR /go/src/github.com/gliderlabs/registrator
VOLUME /go/src/github.com/gliderlabs/registrator
ENTRYPOINT ["go get && go build -ldflags \"-X main.Version dev\" -o /bin/registrator && /bin/registrator"]